version: "3.8"

services:
  frontend-nginx:
    container_name: frontend-nginx
    image: teachertribe-elearn-frontend-nginx
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    ports:
      - "4000:80"
    depends_on:
      - nuxt
  nuxt:
    container_name: nuxt
    image: teachertribe-elearn-nuxt
    build:
      context: .
      dockerfile: ./dockerfiles/nuxt.dockerfile
    volumes:
      - ./src:/app
      - /app/node_modules
  npm:
    container_name: npm
    image: node:21.1.0-slim
    working_dir: /app
    volumes:
      - ./src:/app
    entrypoint: ["npm"]
