version: '3.8'

services:
  app:
    image: teachertribe-elearn
    container_name: teachertribe-elearn
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
  npm:
    container_name: npm
    image: node:20.9.0-alpine3.18
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    entrypoint: ["npm"]


      